id = "tjs"
name = "TJS"
description = "TJS Language Server"
version = "0.1.0"
schema_version = 1
authors = []
repository = "https://github.com/vikfroberg/tjs"

[activation]
auto_update = false

[language_servers.tjs]
name = "TJS"
languages = ["JavaScript"]
